//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedFood
    {
        public int SN { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
        public Nullable<long> Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Foodlist { get; set; }
        public Nullable<int> Foodprice { get; set; }
    }
}
