//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Online_Food_Odering_SystemEntities1 : DbContext
    {
        public Online_Food_Odering_SystemEntities1()
            : base("name=Online_Food_Odering_SystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addtocart> Addtocarts { get; set; }
        public virtual DbSet<BookedFood> BookedFoods { get; set; }
        public virtual DbSet<Foodmenu> Foodmenus { get; set; }
        public virtual DbSet<Userlogin> Userlogins { get; set; }
    }
}
